services:
  db:
    image: postgres
    container_name: todolist_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todolist
    volumes:
      - ./db-data:/var/postgresql/data
    ports: 
      - 5432:5432
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  frontend:
    image: frontend
    build: ./frontend
    restart: always
    ports:
      - 5173:8080
    depends_on:
      - db
    volumes:
      - ./frontend:/app

networks:
  front-end:
  back-end:
