services:
  postgres:
    image: postgres
    container_name: time_manager_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    networks:
      - back-end
  
  adminer:
    image: adminer
    container_name: time_manager_adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - back-end

  vue:
    container_name: time_manager_frontend
    build : 
      context: ./frontend
      args:
        - API_URL=${API_URL}
    restart: always
    ports:
      - 5173:8080
    depends_on:
      - postgres
    networks:
      - front-end
      - back-end

  phoenix:
    container_name: time_manager_phoenix
    build: ./backend
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - postgres
    networks:
      - back-end

networks:
  front-end:
  back-end:
