name: Vue CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.9]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Récupérer tous les fichiers et l'historique complet

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        # Désactiver temporairement le cache npm pour tester
        # cache: 'npm'

    - name: List files in frontend
      run: ls -la ./frontend

    - name: Install Dependencies
      run: npm install
      working-directory: ./frontend

    - name: Build the project
      run: npm run build --if-present
      working-directory: ./frontend
